# Generated by Django 3.1.7 on 2021-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_email_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
