# Generated by Django 3.1.7 on 2021-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_auto_20210410_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
